namespace Empire_ERP.Core.Entities
{
    public class InvoiceReports
    {
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public int? ReportID { get; set; }
        public int? Item { get; set; }
        public int? Branch { get; set; }
        public string? PartyCode { get; set; }
        public string? ActCode { get; set; }
        public string? Salesman { get; set; }
        public string? SActCode { get; set; }
        public int? Group { get; set; }
        public int? Category { get; set; }
        public int? SubCategory { get; set; }
        public int? Barcode { get; set; }
        public int? Size { get; set; }
        public int? Color { get; set; }
        public string? Lot { get; set; }
        public string? Contact { get; set; }
    }

    public class CustomInvoiceReports
    {
        public string? VoucherDate { get; set; }
        public string? vDate { get; set; }
        public string? DUE_DATE { get; set; }
        public string? VoucherNo { get; set; }
        public string? PartyName { get; set; }
        public string? WAITER { get; set; }
        public string? TABLE { get; set; }
        public string? BillMode { get; set; }
        public string? Branch { get; set; }
        public string? Remarks { get; set; }
        public string? ItemId { get; set; }
        public string? ItemName { get; set; }
        public string? ItemName2 { get; set; }
        public string? Color { get; set; }
        public string? Size { get; set; }
        public string? ITEM_CODE { get; set; }
        public string? Barcode { get; set; }
        public string? Region { get; set; }
        public string? Category { get; set; }
        public string? GroupName { get; set; }
        public string? Warehouse { get; set; }
        public string? MenuPage { get; set; }
        public string? MONTH { get; set; }
        public decimal? TOTAL_QTY { get; set; }
        public decimal? TOTAL_R_PRICE { get; set; }
        public decimal? TOTAL_DISC { get; set; }
        public decimal? TOTAL_PRICE { get; set; }
        public decimal? TOTAL_WS_PRICE { get; set; }
        public decimal? STKT_WS_PRICE { get; set; }
        public decimal? TOTAL_EXP { get; set; }
        public decimal? FACTORY_TRANSFER { get; set; }
        public decimal? CASH_SALE { get; set; }
        public decimal? BANK_W_CH { get; set; }
        public decimal? NET_PROFIT1 { get; set; }
        public decimal? TOTAL_COST { get; set; }
        public decimal? NET_PROFIT2 { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Pack { get; set; }
        public decimal? TotalPack { get; set; }
        public decimal? Weight { get; set; }
        public int? MenuId { get; set; }
        public decimal? POSQty { get; set; }
        public decimal? Debit { get; set; }
        public decimal? Credit { get; set; }
        public decimal? Rate { get; set; }
        public decimal? Amt { get; set; }
        public decimal? Tax { get; set; }
        public decimal? InclTax { get; set; }
        public decimal? CSET { get; set; }
        public decimal? NetAmt { get; set; }
        public decimal? Cash { get; set; }
        public decimal? CashTax { get; set; }
        public decimal? BankTax { get; set; }
        public decimal? PartyTax { get; set; }
        public decimal? TaxAmt { get; set; }
        public decimal? ADV_TAX { get; set; }
        public decimal? ADV_TAX_AMT { get; set; }
        public decimal? totalSales { get; set; }
        public decimal? CardType { get; set; }
        public decimal? Party { get; set; }
        public decimal? Stock { get; set; }
        public decimal? StockIn { get; set; }
        public decimal? StockOut { get; set; }
        public decimal? MDisc_Amt { get; set; }
        public decimal? Disc { get; set; }
        public decimal? ReturnAmt { get; set; }
        public decimal? ReturnDisc { get; set; }
        public string? SubCategory { get; set; }
        public string? Desc { get; set; }
        public decimal? Balance { get; set; }
        public decimal? Balance2 { get; set; }
        public decimal? TotalBalance { get; set; }
        public decimal? Total { get; set; }
        public decimal? Advance { get; set; }
        public decimal? Price { get; set; }
        public decimal? WholePrice { get; set; }
        public decimal? ShopPrice { get; set; }
        public decimal? PPrice { get; set; }
        public decimal? WPrice { get; set; }
        public decimal? SPrice { get; set; }
        public string? SizeSet { get; set; }
        public string? LINK { get; set; }
        public int? TRAN_ID { get; set; }
        public int? MenuParentCode { get; set; }
        public int? PbRate { get; set; }
        public int? PAmt { get; set; }
        public int? WRate { get; set; }
        public decimal? WAmt { get; set; }
        public string? BTransfer { get; set; }
        public string? BName { get; set; }
        public string? ActName { get; set; }
        public string? Mobile { get; set; }
        public string? CName { get; set; }
        public string? CAdd { get; set; }
        public decimal? Recv { get; set; }
        public string? Mode { get; set; }
        public string? CMOB { get; set; }
        public string? CNAME { get; set; }
        public string? CADD { get; set; }
        public string? SRB_INV { get; set; }
        public string? Salesman { get; set; }
        public decimal? Percentage { get; set; }
        public decimal? Commission { get; set; }
        public decimal? DeliveryCharges { get; set; }
        //addUnit
        public string? Unit { get; set; }
        public List<dynamic> detail { get; set; }
    }
}