<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Reports\BarcodeReportWithTwoLabelsAndColor.rdlc" />
    <None Remove="Reports\BarcodeReportWithTwoLabels.rdlc" />
    <None Remove="Reports\Datasets\BarcodeReportDataset - Copy.xsd" />
    <None Remove="Reports\Datasets\BarcodeReportDataset.xsd" />
    <None Remove="Reports\Datasets\InvoiceReport.rdlc" />
    <None Remove="Reports\DCPrintReport.rdlc" />
    <None Remove="Reports\DCPrintReportWithRate.rdlc" />
    <None Remove="Reports\DeliveryChallan.rdlc" />
    <None Remove="Reports\InvoiceReport.rdlc" />
    <None Remove="Reports\SakhiBuyer.rdlc" />
    <None Remove="Reports\SakhiBuyerWoCmt.rdlc" />
    <None Remove="Reports\DeliveryOrder.rdlc" />
    <None Remove="Reports\List.rdlc" />
    <None Remove="Reports\OLDDCPrintReport - Copy.rdlc" />
    <None Remove="Reports\OLDInvoiceReport(4).rdlc" />
    <None Remove="Reports\OLDInvoiceReport.rdlc" />
    <None Remove="Reports\OLDInvoiceReport_Old.rdlc" />
    <None Remove="Reports\OLDSTKTRPrintReport.rdlc" />
    <None Remove="Reports\PrintReport.rdlc" />
    <None Remove="Reports\SalesInvoice.rdlc" />
    <None Remove="Reports\SalesInvoice_Old.rdlc" />
    <None Remove="Reports\SalesTax - Copy.rdlc" />
    <None Remove="Reports\SalesTax.rdlc" />
    <None Remove="Reports\STKTRPrintReport.rdlc" />
    <None Remove="Reports\StockTransferReportLabel.rdlc" />
    <None Remove="Reports\CashPayment.rdlc" />
    <None Remove="Reports\PackingList.rdlc" />
    <None Remove="Reports\Shipment.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Reports\BarcodeReportWithoutDetail.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\BarcodeReportWithDetail.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\BarcodeReportWithTwoLabelsAndColor.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\InspectionServiceCharges.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\DailyProduction.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\BillOfMaterialWoRate.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\DeliveryOrderReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PartyToParty.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SaleInvoiceDDJ.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SalesInvoiceImages.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SalesInvoiceImages_Old.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\StockTransferPeter.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PurchaseBook.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PartyReceipt.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\MaterialReq.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PurchaseOrder.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PurchaseReq.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\GatePass.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\JournalVoucher.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Datasets\InvoiceReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\DCPrintReportWithRate.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\IGMReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\List.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PackingList.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PrintReport - Copy.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SakhiBuyerWoCmt.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Shipment.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SalesTax - Copy.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SalesTax.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\BillOfMaterial.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SalesInvoice.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\DeliveryChallan.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SalesInvoice_Old.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\OLDDCPrintReport - Copy.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\OLDInvoiceReport%284%29.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\InvoiceReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SakhiBuyer.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\DeliveryOrder.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\OLDInvoiceReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\OLDInvoiceReport_Old.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\DCPrintReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\OLDSTKTRPrintReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\STKTRPrintReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\PrintReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\StockTransferReportLabel.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\CashPayment.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\BarcodeReportWithTwoLabels.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Datasets\BarcodeReportDataset.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>BarcodeReportDataset.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdfAll" Version="1.0.5" />
    <PackageReference Include="evopdf" Version="12.0.0" />
    <PackageReference Include="GeoCoordinate.NetCore" Version="1.0.0.1" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="HtmlRenderer.WinForms" Version="1.5.0.6" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="MailKit" Version="4.12.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="7.0.15" />
    <PackageReference Include="Microsoft.Web.Administration" Version="11.1.0" />
    <PackageReference Include="Nominatim.API" Version="2.0.0" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.21" />
    <PackageReference Include="RestSharp" Version="106.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Empire_ERP.Core\Empire_ERP.Core.csproj" />
    <ProjectReference Include="..\Empire_ERP.Infrastructure\Empire_ERP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Reports\Datasets\BarcodeReportDataset - Copy.Designer.cs">
      <DependentUpon>BarcodeReportDataset - Copy.xsd</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Reports\Datasets\BarcodeReportDataset.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BarcodeReportDataset.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Client\UserFiles\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Employee\Index.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\Customjs\empr_StockTransferRequisition.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
